TITLE1 "EMPTY MEANS, RANDOM INTERCEPT MODEL -- (WORST BASELINE CASE)";
PROC MIXED DATA = group_output_df COVTEST NOCLPRINT NAMELEN = 100 IC METHOD = REML;
	CLASS school_sid SY_ind;
	MODEL WDRAW_ORIG_YR2_RT = / SOLUTION DDFM = SATTERTHWAITE;
	RANDOM INTERCEPT / G V VCORR TYPE = UN SUBJECT = school_sid;
	REPEATED SY_ind / R RCORR TYPE = VC SUBJECT = school_sid;
	ODS OUTPUT CovParms = CovEmpty;
run; TITLE1;

TITLE1 "Random Quadratic Time Model -- (RANDOM SLOPES & RANDOM INTERCEPT)";
PROC MIXED DATA = group_output_df COVTEST NOCLPRINT NAMELEN = 100 IC METHOD = REML;
	CLASS school_sid SY_ind;
	MODEL WDRAW_ORIG_YR2_RT = time1 time1 * time1 / SOLUTION DDFM = SATTERTHWAITE;
	RANDOM INTERCEPT time1 time1 * time1 / G GCORR V VCORR TYPE = UN SUBJECT = school_sid;
	REPEATED SY_ind / R TYPE = VC SUBJECT = school_sid;
	ODS OUTPUT InfoCrit = FitRandQuad;
run; TITLE1;





TITLE1 "EMPTY MEANS, RANDOM INTERCEPT MODEL -- (WORST BASELINE CASE)";
PROC MIXED DATA = group_output_df COVTEST NOCLPRINT NAMELEN = 100 IC METHOD = REML;
	CLASS school_sid SY_ind;
	MODEL WDRAW_ORIG_YR2_RT = / SOLUTION DDFM = SATTERTHWAITE;
	RANDOM INTERCEPT / G V VCORR TYPE = UN SUBJECT = school_sid;
	REPEATED SY_ind / R RCORR TYPE = VC SUBJECT = school_sid;
	ODS OUTPUT CovParms = CovEmpty;
run; TITLE1;

TITLE1 "RANDOM LINEAR TIME MODEL -- (RANDOM SLOPE & RANDOM INTERCEPT)";
PROC MIXED DATA = group_output_df COVTEST NOCLPRINT NAMELEN = 100 IC METHOD = REML;
	CLASS school_sid SY_ind;
	MODEL WDRAW_ORIG_YR2_RT = time1 AVGSTUDSENT / SOLUTION DDFM = SATTERTHWAITE;
	RANDOM INTERCEPT time1 AVGSTUDSENT / G GCORR V VCORR TYPE = UN SUBJECT = school_sid;
	REPEATED SY_ind / R TYPE = VC SUBJECT = school_sid;
	ODS OUTPUT CovParms = CovRandLin InfoCrit = FitRandLin;
run; TITLE1;

TITLE1 "RANDOM LINEAR TIME MODEL -- (RANDOM SLOPE & RANDOM INTERCEPT)";
PROC MIXED DATA = group_output_df COVTEST NOCLPRINT NAMELEN = 100 IC METHOD = REML;
	CLASS school_sid SY_ind;
	MODEL WDRAW_ORIG_YR2_RT = time1 AVGSTUDSENT num_reviews / SOLUTION DDFM = SATTERTHWAITE;
	RANDOM INTERCEPT time1 AVGSTUDSENT num_reviews / G GCORR V VCORR TYPE = UN SUBJECT = school_sid;
	REPEATED SY_ind / R TYPE = VC SUBJECT = school_sid;
	ODS OUTPUT CovParms = CovRandLin InfoCrit = FitRandLin;
run; TITLE1;


